[package]
name = "lumina-patterns"
version = "0.1.0"
authors = ["simon.larsson <simon.larsson@elits.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
